# The base hostname & protocol for your site, e.g. https://example.com
url: "https://olivierobert.com/"

permalink: pretty
template_engine: liquid

# timezone: America/Los_Angeles

# pagination:
#   enabled: true

collections:
  notes:
    output: true
    permalink: pretty
